export {default as TrafficAllocate} from './TrafficPoliceAllocation/TrafficAllocate'
export {default as MaskAllocate} from './MaskPoliceAllocation/MaskAllocate'
export {default as ChallanAllocate} from './ChallanDashboard/ChallanAllocate'
export {default as TrafficInformation1} from "./TrafficInformation1/TrafficInformation1"
export {default as TrafficInformation2} from "./TrafficInformation2/TrafficInformation2"
export {default as UrbanInformation1} from "./UrbanInformation1/UrbanInformation1"
export {default as UrbanInformation2} from "./UrbanInformation2/UrbanInformation2"
export {default as CameraInformation} from "./CameraInformation/CameraInformation"
export {default as UnsafeAreas} from "./UnsafeAreas/UnsafeAreas"
export {default as RealTimeMask} from "./RealTimeMask/RealTimeMask"
export {default as RealTimeTraffic} from "./RealTimeTraffic/RealTimeTraffic"